### ISSUE TITLE
pycompat: 'dispose' is missing exception specification 'noexcept'

### ISSUE THREAD

**Issue by fiedl** [fiedl/hole-ice-install#6]
Trying a current build with github actions, I'm running into **'dispose' is missing exception specification 'noexcept'**.

Build log: https://github.com/fiedl/hole-ice-install/commit/b48feb716ff730d9e75b1757707b3148b26290cf/checks#step:3:7022

```
[ 38%] Building CXX object tableio/CMakeFiles/tableio-pybindings.dir/private/pybindings/I3CSVTableService.cxx.o
7021
[ 38%] Building CXX object dataclasses/CMakeFiles/dataclasses-pybindings.dir/private/pybindings/I3DetectorStatus/MapOMKeyI3DOMStatus.cxx.o
7022
/Users/runner/icecube/software/icecube-simulation-V06-01-01/src/steamshovel/private/scripting/pycompat.cpp:55:24: error: 'dispose' is missing exception specification 'noexcept'
7023
BOOST_PP_SEQ_FOR_EACH( SPECIALIZE, _, SHOVELART_GIL_PROTECTED_TYPES )
7024
                       ^
7025
/usr/local/include/boost/smart_ptr/detail/sp_counted_impl.hpp:171:18: note: previous declaration is here
7026
    virtual void dispose() BOOST_SP_NOEXCEPT
7027
                 ^
7028
/Users/runner/icecube/software/icecube-simulation-V06-01-01/src/steamshovel/private/scripting/pycompat.cpp:55:24: error: 'dispose' is missing exception specification 'noexcept'
7029
BOOST_PP_SEQ_FOR_EACH( SPECIALIZE, _, SHOVELART_GIL_PROTECTED_TYPES )
7030
                       ^
7031
/usr/local/include/boost/smart_ptr/detail/sp_counted_impl.hpp:171:18: note: previous declaration is here
7032
    virtual void dispose() BOOST_SP_NOEXCEPT
7033
                 ^

make: *** [all] Error 2
7218
##[error]Process completed with exit code 2.
```

**Comment by fiedl** [comment]
I've narrowed it down to the installed boost version.

Compiling fails with boost 1.70.

Compiling works with boost 1.68.

**Comment by fiedl** [comment]
This has been fixed by downgrading boost to 1.69.

https://github.com/fiedl/hole-ice-install/commit/80348e728980b627a85718e4749f99f60552c89c/checks

I've also provided brew formulae and bottles:
https://github.com/IceCube-SPNO/homebrew-icecube/pull/35
